# **CHƯƠNG I: NỀN TẢNG**

## **0. Deep Learning là gì?**

Deep Learning là một mảng con của học máy (Machine Learning) nhắc về việc đưa thứ gì đó (dữ liệu) thành một con số và đi tìm **patterns** từ những con số đó

=> Máy tính tìm patterns thông qua code và toán

> AI > Machine Learning > Deep Learning

So sánh 1 chút về thực tế và học máy

*Ta có quy trình nấu ra một món đối với cách truyền thống từ nguyên liệu qua công thức để thành món ăn nhưng với học máy ta có nguyên liệu món ăn và ta tìm ra công thức*

## **1. Tại sao sử dụng Machine Learning/Deep Learning?**

Việc sử dụng Machine Learning và Deep Learning giúp tìm ra các giải pháp đối với những vấn đề đưa ra nhiều kết quả khác nhau và tìm điểm chung của quy luật liên quan giữa chúng  

Dùng Deep Learning khi:
- Vấn đề dài lập thành các danh sách mà phương pháp truyền thống không tìm được
- Liên tục thay đổi theo môi trường
- Khai phá chiều sâu với lượng thu thập dữ liệu lớn

Không dùng Deep Learning khi:
- Cần giải thích nhiều do Deep Learning nhiều thông số thuật toán không thể giải thích bằng ngôn ngữ người
- Khi lựa chọn các phương pháp truyền thống lớn hơn
- khi lỗi là không chấp nhận được
- không có nhiều dữ liệu

## **2. Machine Learning Vs. Deep Learning?**

Machine Learning như cách truyền thống tìm luật thông qua dữ liệu có tổ chức dạng bảng,...

Deep Learning tìm luật thông qua các dữ liệu không cấu trúc: audio, text, hình ảnh. Thuật toán là neuron  

Các thuật toán phổ biến:
- ML: Random, Tree, SVN, KNN, ...
- DL: Neural Networks, CNN, RNN, Transformer, ...

## **3. Neural Networks là gì?**

*Ví dụ ta có các dữ liệu phi cấu trúc* -> *Chuyển các kiểu dữ liệu đó thành dạng số trước khi sử dụng mạng nơ ron gọi là numberical ecoding* -> *chọn mạng nơ ron phù hợp gợi là học cách tổ chức thông qua patterns, features, weights* -> *Trả về các tham số đầu ra* -> *chuyển thành output mà con người hiểu được*   

Mạng nơ ron sẽ chia thành 3 layer -> (1) Input Layer chứa các hàm kích hoạt (2) Hidden layer gồm các công thức toán biến đổi nhằm học đặc trưng  (3) Output layer xuất trả về các tham số

Mỗi layer có thể kết hợp bởi cac hàm linear hoặc non-linear

## **4. Các loại của học?**

- **Học giám sát**

Khi có dữ liệu và label và thuật toán tìm ra quy luật dựa trên label cho sẵn để dự đoán cái mới

- **Học không giám sát - tự giám sát**

Chỉ có dữ liệu và không có cung cấp bất kỳ label có sẵn nào dùng cho nhạn xét phân cụm tìm mối quan hễ giữa các parttens

- **Học tương tác**

Một model học và tương tác với model khác một model đánh giá việc học cua model còn lại dựa trên lý thuyết học tăng cường

## **5. Deep Learning dùng để làm gì thực tế??**

- Hệ thống gợi ý
- Dịch máy, ghi âm giọng nói (seq2seq)
- Thị giác máy tính, xử lý ngôn ngữ tự nhiên (classificatrion, regression)

## **6. PyTorch là gì và sao lại sử dụng?**

- PyTorch framework cho Deep Learning
- Chạy code nhanh với DL (chạy thông qua GPU)
- Truy cập nhiều model DL
- Nhiều bước: chuẩn bị dữ liệu, model, deploy
- Tổ chức uy tín bởi facebook và mã nguồn mở
- Sử dụng nhiều cho ML và DL, dùng nhiều cho các dự án thực tế

## **7. GPU/TPU là gì?**

GPU là card đồ họa thực hiện nhiệm vụ xử lý các thông số hiên thị thực hiện các phép tính song song khi huấn luyện model TPU chính là chip sử lý Tensor có nhiệm vụ tương tự như GPU được sử dụng khi chạy PyTorch code. tuy nhiên sử dụng GPU phổ biếm hơn

## **8. Tensor là gì?**

Là cấu trúc dữ liệu giống với mảng nhiều chiều biểu diễn các dữ liệu phi cấu trúc thành những con số và lưu chúng thành một hoặc nhiều mảng dược sử dụng nhiều cho Deep Learning

Là cấu trúc tổng quát chung cho scalar, vector, matrix khi thưc hiện huấn luyện kết quả đầu vào và đầu ra cũng sẽ là một tensors















# **CHƯƠNG II: PHẦN LÝ THUYẾT CỐT LÕI**

In [1]:
# Khai báo thư viện PyTorch
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) # Phiên bản PyTorch

2.10.0+cpu


## **9. Giới thiệu về tensors**

### **Khởi tạo tensors**

PyTorch sử dụng `torch.Tensor()` để khởi tạo = https://docs.pytorch.org/docs/stable/tensors.html

Quy tắc đạt tên biến đói với scalar, vecto thì biến chữ thưỡng còn matrix hay tensors thì biến viết hoa

In [2]:
# scalar - số vô hướng
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # DO là số lên số chiều là 1

0

In [4]:
# Chuyển tensor thành số Python

scalar.item()

7

In [5]:
# Khởi tạo vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim # Số chiều

1

In [7]:
vector.shape # Xuất ra trong tensors số phần tử

torch.Size([2])

In [8]:
# Khởi tạo matrix - Ma trận
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim # Có 2 chiều tương đương hai dấu ngoặc vuông

2

In [10]:
MATRIX.shape # Xuất số ahfng số cột

torch.Size([2, 2])

In [11]:
MATRIX[1] # Xuấ hàng 2 ma trận

tensor([ 9, 10])

In [12]:
# Khởi tạo tensors
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim # Số chiều tương ứng với ngoặc vuông

3

In [14]:
TENSOR.shape # Tính từ ngoặc vuông ngoài cùng vô trong xét cột xét hàng

torch.Size([1, 3, 3])

### **Tensors ngẫu nhiên**

Sử dụng random tensors giúp cho các mạng nơ ron học được thông qua các tensors ngãu nhiên và có thể điều chỉnh sao cho các con số ngẫu nhiên phù hợp để diễn tả

`Bắt đầu với số ngẫu nhiên -> Nhìn dữ liệu -> Update dữ liệu ngaaxi nhiên -> Nhìn dữ liệu -> Update`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [15]:
# Tạo tensors ngẫu nhiên với size 3, 4
random_tensors = torch.rand(1, 3, 4)
random_tensors

tensor([[[0.7918, 0.6969, 0.2105, 0.6894],
         [0.7715, 0.1426, 0.3357, 0.4441],
         [0.7076, 0.5001, 0.0724, 0.4192]]])

In [16]:
# Khởi tạo tensor với shape gần giống với tensor ảnh
random_image_size_tensors = torch.rand(size=(224, 224, 3)) # chiều cao, chiều rộng, channel màu (channel mầu tức là có bao nhiều tấm ảnh màu riêng lẻ ghép lại với nhau)

random_image_size_tensors.shape, random_image_size_tensors.ndim # Số chiều là 3

(torch.Size([224, 224, 3]), 3)

In [17]:
# tensors chỉ có 1 và 0

# Khởi tạo tensors toàn không
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Khởi tạo tensors toàn 1
one = torch.ones(size=(3, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
one.dtype # Kiểu dữ liệu của thành phần có tỏng tensors

torch.float32

### **Tạo tensors trong khoảng**

In [20]:
# Sử dụng torch.range()

one_to_ten = torch.arange(0, 11) # arange(start, end, step)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Khởi tạo tensors like nhân bản tensors mà cũng shape nhưng toàn 0
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **DataType của Tensors**

Chuyển thành 32 hoặc 16 bit giúp bộ nhớ dễ dàng lưu trữ và thực hiện ghi nhớ chính xác nhanh hơn

**Tensors datatypes la fmootj trong 3 điều đáng lưu ý dễ sai khi thực hiện Pytorch**

1. tensors không phải là kiểu dữ liệu đúng
2. tensors không đúng device
3. tensors không đúng shape

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)



In [22]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None # DataTypoe trong tensors là gì
                                              , device=None, # Thiết bị sử dụng lưu trữ tensors
                                                requires_grad=False) # Có cần track gradients hay không

float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16) # Chuyển kiểu dữ liệu
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor # Vẫn thực hiện với các phép tính toán

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### **Lấy thống tin tensors (thuộc tính Tensor)**

1. tensors không phải là kiểu dữ liệu đúng - get datatype dùng `tensor.dtype`
2. tensors không đúng device - get device dùng `tensor.device`
3. tensors không đúng shape - get shape dùng `tensor.shape`

In [28]:
# Khởi tạo tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8897, 0.3751, 0.2221, 0.0875],
        [0.2081, 0.0158, 0.9381, 0.1412],
        [0.9132, 0.2713, 0.2941, 0.7675]])

In [29]:
some_tensor.size() # = some_tensor.shape

torch.Size([3, 4])

In [30]:
# Tìm kiếm về tensor
print(some_tensor)
print(f"DataType của tensors: {some_tensor.dtype}")
print(f"Device của tensors: {some_tensor.device}")
print(f"Shape của tensors: {some_tensor.shape}")

tensor([[0.8897, 0.3751, 0.2221, 0.0875],
        [0.2081, 0.0158, 0.9381, 0.1412],
        [0.9132, 0.2713, 0.2941, 0.7675]])
DataType của tensors: torch.float32
Device của tensors: cpu
Shape của tensors: torch.Size([3, 4])


## **10. Tương tác với Tensors**

Bao gồm
- Cộng
- Trừ
- Nhân (từng phần tử)
- Chia
- Nhân ma trận
- Thay đổi kiểu dữ liệu, chiều, tổ chức tensor
- Thêm và loại bỏ chiều của tensor

In [31]:
# Khởi tạo tensor
tensor = torch.tensor([1, 2, 3])
tensor + 100 # Cộng các phần tử đều cộng 100

tensor([101, 102, 103])

In [32]:
# Nhân tensor cho 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Trừ 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Xây dựng hàm
torch.mul(tensor, 10) # Nhân tensor cho 10

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10) # Cộng tensor cho 10

tensor([11, 12, 13])

### **Nhân ma trận**

Hai cách chính để niểu diễn nhận ma trận trong mạng nơ ron và học sâu:

1. Nhân các phần tử:  Nhân từng phần tử trong ma trận với từng phần tử trong ma trận kia
2. Nhân ma trận: Phẩn từ dòng thứ i sẽ nhân với phần tử cột j để hình thành phần tử dòng i cột j sau khi cộng lại. Đặc biệt là số hàng ma trận này phải bằng số cột mâ trận kia  (dùng dấu .)

Thông tin thêm: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Hai lỗi phổ biến khi nhân ma trận

1. Các ma trận phải chung chiều với nhau tức số hàng ma trận này là số cột ma trận kia:
- `(3, 2) @ (3, 2)` không đúng
- `(2, 3) @ (3, 2)` đúng
- `(3, 2) @ (2, 3)` đúng

2. Chiều của ma trận kết quả sẽ là shape sau khi loại bỏ 2 hàng và cột trùng

- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [36]:
# Nhân từng phần tử
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Kết quả: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Kết quả: tensor([1, 4, 9])


In [37]:
# Nhân ma trận
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Nhân ma trận bằng tay

1*1 + 2*2 + 3*3

14

In [40]:
tensor @ tensor

tensor(14)

In [41]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i] # Tính thời gian nhân ma trận qua vòng lặp
print(value)

tensor(14)
CPU times: user 1.43 ms, sys: 204 µs, total: 1.63 ms
Wall time: 6.31 ms


In [42]:
%%time
torch.matmul(tensor, tensor) # Tính thời gian nhân ma trận qua hàm torch

CPU times: user 70 µs, sys: 10 µs, total: 80 µs
Wall time: 84.9 µs


tensor(14)

Dùng hàm sẽ nhanh hơn dùng vòng lặp

Truy cập: http://matrixmultiplication.xyz/ để xem mình họa nhân ma trận

### **Lỗi phổ biến trong Học sâu là sai shape**

In [43]:
# Shape khi nhân ma trân
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


torch.mm(tensor_A, tensor_B) # torch.mm là torch.matmul


# Lỗi chung shape


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


Để fix tensor shape ta cần điều chỉnh 1 trong 2 shape của ma trận sử dụng **transpose**

**Transpose** chuyển cột thạnh hàng và thành hàng thành cột

In [44]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
# phếp nhân ma trận này hoạt động khi ma trận B chuyển vị
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} chung shape trên, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) chung shape trên, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### **Tìm min, max, nean, sum, etc của tensor**

In [48]:
# Khởi tạo tensor
x = torch.arange(0, 100, 10)
x.dtype # Kiểu dữ liệu int64

torch.int64

In [47]:
# Tìm mean = note: kiểu dữ liệu hàm yêu cầu là float32 bắt buộc
print("===================== Mean ==========================")
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean()) # Lưu ý chuyển về datatype đúng với hàm

# Tìm giá trị lớn nhất
print("===================== Max ==========================")
print(torch.max(x))
print(x.max())

# Tìm giá trị nhỏ nhất
print("========================== Min ==========================")
print(torch.min(x))
print(x.min())

===================== Mean ==========================
tensor(45.)
tensor(45.)
===================== Max ==========================
tensor(90)
tensor(90)
========================== Min ==========================
tensor(0)
tensor(0)


**Lưu ý**

`torch.mean()` yteeu cầu kiểu dữ liệu của tensor phải là `float32` (phổ biến nhất) haowjc các kiểu dữ liệu phải chung với nhau  

In [49]:
# Tìm tổng
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### **Tìm vị trí min, max của tensor**

Ta có thể sử dụng `torch.argmax()` dể tìm vị trí mà tại đó phần tử trong tensor là lớn nhất `torch.argmin()` để tìm vị trí phần tử nhỏ nhất (giúp ích trong hàm kich hoạt softmax)

In [50]:
# Tìm vị trí mà tại đó phần tử là max
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Index (vị trí) của phần tử max và min trong tensor
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### **Thay đổi kiểu dữ liệu tensor**

Để thay đổi kiểu dữ liệu của tensor sử dụng `torch.Tensor.type(dtype=None)` với `dtype` là kiểu dữ liệu cần thay đổi

In [51]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [52]:
# Chuyển kiểu dữ liệu tensor thành float16
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [53]:
# Chuyển kiểu dữ liệu tensor thành int8
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Lưu ý**

Các con số sau kiểu dữ liệu (8, 32, 64, ...) khi số càng bé thì việc lưu trữ các kiểu dữ liệu đó càng thấp ít tốn dung lượng hơn, trong quá trình học của máy cũng sẽ nhanh tuy nhiên đánh đổi là khả năng chính xác của mô hình cũng sẽ giảm

Xem thêm: https://docs.pytorch.org/docs/2.11/tensors.html

### **Đổi chiều chuyển thành stacking, squeezing và unsqueezing**

Đôi khi ta muốn thay đổi hàng và cột hoặc thay đổi chiều của tensor mà không thay đổi các giá trị trong chúng. Ta sử dụng các phương pháp sau:

- `torch.reshape(input, shape)`: để đổi shape nếu không có liên tục tự động copy dữ liệu   
- `torch.view(shape)`: trả về view mới đối với tensor trong nhiều shape khác nhau nhưng với dữ liệu giống với tensor gốc
- `torch.stack(tensors, dim=0)`: Chồng các tensor lên nhau và tạo ra một chiều mới. Các tensor phải có cùng kích thước.
- `torch.squeeze(input)`: Loại bỏ chiều có kích thước là 1
- `torch.unsqueeze(input)`: Thêm chiều mới có kích thước là 1
- `torch.permute(intput, dims)`: Dùng để hoán đổi thứ tự các chiều không gian.

In [54]:
# Dùng reshape
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [55]:
# Thêm một chiều
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [56]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [57]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [58]:
# Xếp tensor lên những tensor còn lại
x_stacked = torch.stack([x, x, x, x], dim=0) # 0: theo hàng, 1: theo cột
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [59]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Loại bỏ chiều vừa thêm trong tensor x_squeezed
x_squeezed = x_reshaped.squeeze() # Dùng squeeze
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [60]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Thêm một chiều với unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [61]:
# Tạo tensor ban đầu
x_original = torch.rand(size=(224, 224, 3))

# Điều chỉnh shape thành các vị trí khác nhau
x_permuted = x_original.permute(2, 0, 1) # chuyển axis 0->2, 1->0, 2->1

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Lưu ý**

Cả `permute` và `view` đều chạy trên dữ liệu chính do đó mà khi thay đổi các dữ liệu trong tensor tạo ra bởi chùng thì sẽ ảnh hưởng đến tensor gốc

## **11. Indexing (Chọn dữ liệu từ tensor)**

Dôi khi chúng ta muốn lấy duy nhất một dữ liệu từ tensor (ví dụ chỉ các dữ liệu trong cột 1 hàng 2) để làm điều đó sử dụng indexing

Ta đã được biết indexing tronG Python list hoặc Numpy arrays tương tự Pytorch tensor cũng như vậy

In [62]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing sẽ đi từ ngoài vào trong dựa theo ngoặc vuông

In [63]:
# Sử dụng indexing trong ngoặc vuông
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Có thể sử dụng `:` để nó rằng "tát cả giá trị có trong chiều này" và sau đó `.` để thêm một chiều khác

In [64]:
x[:, 0] # Lấy tất cả các giá trị trong chiều đầu tiên trong chiều thứ 2 của tensor

tensor([[1, 2, 3]])

In [65]:
x[:, :, 1] # Lấy tất cả các giá trị trong chiều đầu tiên và thứ 2 trong chiều thứ 2 của tensor

tensor([[2, 5, 8]])

In [66]:
x[:, 1, 1] # Lấy duy nhất 1 giá trị của tensor đầu tiên nhưng chỉ lấy tensor thứ 2 vị trí 2

tensor([5])

In [67]:
# Lấy index 0 của chiều thứ 1 và thứ 2 và tất cả giá trị của chiều thứ 3
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Thực hành nhiều với indexing sẽ giúp ta thành thục nso hơn

### **Pytorch tensors & Numpy**

Hai phương thức chính để sử dụng Numpy chung với Pytorch là:

- `torch.from_numpy(ndarray)`: Chuyển Numpy array thành Pytorch tensor

- `torch.Tensor.numpy()`: Chuyển Pytorch tensor thành Numpy array


In [68]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

**Lưu ý**

Mặc định Numpy array là `float64` và nếu chuyển thành tensor sẽ giữ nguyên kiểu dữ liệu

Tuy nhiên một số Pytorch sử dụng `float32` do đó khi chuyển muốn thực hiện tính toán ta cần chuyển về đúng kiểu dữ liệu


In [69]:
# Thay đổi array giữ lại tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
# Chuyển tensor thành Numpy array
tensor = torch.ones(7) # Tạo tensor với kiểu dữ liệu float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [72]:
# Thay đổi tensor vè giữ nguyên array
tensor = tensor + 1
tensor, numpy_tensor # Không tạo bản sao

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### **Tái sử dụng**

Khi học về mạng nơ ron và học máy ta sẽ bắt đầu khám phá rằng tính ngẫu nhiên của phép toán này là bao nhiêu

Ta biết rằng khi mạng nơ ron học bằng cách bắt dầu với con số ngẫu nhiên để mô tả một thiết kế của dữ liệu và cố gắng cải thiện con số ngẫu nhiên đó sử dụng các phép tính quan hệ tensor. Nói ngắn gọn

> Bắt đầu với số ngẫu nhiên -< Phép quan hệ tensor -> Cái thiện

Tuy nhiên không phải ngẫu nhiên lúc nào cũng cần thiết. Lấy ví dụ khi viết một thuật toán và so sánh nhiều thuật toán khác nhau trên cũng một dự liệu ngẫu nhiên nào đó. Đó chính là lúc việc tái sử dụng xuất hiện


In [76]:

import torch

# Tạo 2 tensor ngẫu nhiên
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9065, 0.3584, 0.2248, 0.3769],
        [0.8794, 0.8861, 0.4920, 0.1571],
        [0.3287, 0.3876, 0.9994, 0.7697]])

Tensor B:
tensor([[0.6493, 0.8090, 0.8282, 0.9174],
        [0.8279, 0.3044, 0.6983, 0.9698],
        [0.0056, 0.7069, 0.5271, 0.2367]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Ta sử dụng `torch.manual.seed(seed)` để thực hiện giữ nguyên các giá trị ngẫu nhiên

In [82]:
import torch
import random

# Set seed
RANDOM_SEED=42 # Giá trị seed
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# reset seed sau mỗi lẫn hàm rand() được gọi
# Nếu không có điều này, tensor_D sẽ khác giá trị to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # phải set trước để cùng giá trị
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Đọc thêm**

- PyTorch: https://docs.pytorch.org/docs/2.11/notes/randomness.html
- Wikipedia: https://en.wikipedia.org/wiki/Random_seed